@startuml
'https://plantuml.com/class-diagram

class Board
class Player
class Space
class GameController
class AppController
interface ViewObserver
class LobbyClient
class SaveLoad
class BoardView
class SpaceView
class MenuBar
class StartGame
abstract class FieldAction
interface Observer
abstract class Subject
class Reboot
class StartSpace
class ConveyorBelt
class Pit
class Gears
class Checkpoint
class PushPanel
class Lobby
interface ILobbyClient


AppController"1" - "1"StartGame
AppController"1" *-- "1"GameController
AppController"1" --  "1"LobbyClient
GameController"1"  --* "1"Board
GameController"1" *--  "1"BoardView
BoardView"0..*"  ..|>  "1"ViewObserver
SpaceView"0..*" ..|> "1"ViewObserver
AppController"1" -- "1"MenuBar
Board"1" -- "1"BoardView
LobbyClient"1"-- "1"SaveLoad
Board"1" -- "1"SaveLoad
ViewObserver"0..*" --|> "1"Observer
Reboot"1..*" --|> "1"FieldAction
StartSpace"1..*" -|> "1"FieldAction
ConveyorBelt"0..*" --|> "1"FieldAction
Pit "0..*" -|> "1"FieldAction
Gears "0..*" --|> "1"FieldAction
FieldAction"1" <|-- "1..*" Checkpoint
FieldAction"1" <|-- "0..*"PushPanel
LobbyClient"0..*" ..|> "1"ILobbyClient
Lobby"0..*" -- "1"LobbyClient
Lobby"0..1" -- "1"AppController
Board"0..*" --|> "1"Subject
Player"0..*" --|> "1"Subject
Space"0..*" --|> "1"Subject
Board"1" *- "1..*"Space
Space"1" - "0..1"Player
Player"0.." -- "1"SpaceView
Space"1" *-- "1"SpaceView
Space"1..*" -- "1"BoardView
GameController"1" -- "0..*"Space
GameController"1" -- "2..6"Player
FieldAction"1..*" -- "1"GameController
BoardView"1" -- "1..*"SpaceView
MenuBar"1" -- "1"StartGame
FieldAction"0..1" - "1"SpaceView
GameController"1" -- "0..*"SpaceView
Player"2..6" --* "1" Board
FieldAction "0..1" -- "1" Space

@enduml